### PR TITLE
adding new function for making our blockchain more tamper_proof than before

### PR DESCRIPTION
**Pull request by cs-joy**

### CODE REVIEW

**Review by squidboop — COMMENTED** [review]
thank you. let me execute

**Comment by squidboop** [comment]
> thank you. let me execute

though, there was a typo

**Comment by cs-joy** [comment]
> > thank you. let me execute
> 
> though, there was a typo

ohh, i didn't execute on my machine though, there are one more line need to add `console.log(this.hash)` which is need to set inside of the `mineBlock()` method. and the typo in the while loop,(missing closed parenthesis).

thank you for notifying me.

**Comment by squidboop** [comment]
> > > thank you. let me execute
> > 
> > 
> > though, there was a typo
> 
> ohh, i didn't execute on my machine though, there are one more line need to add `console.log(this.hash)` which is need to set inside of the `mineBlock()` method. and the typo in the while loop,(missing closed parenthesis).
> 
> thank you for notifying me.

it's executing successfully. thanks

**Pull request merged**
